cask_args appdir: '/Applications'

tap 'homebrew/bundle'
brew 'antigen'

cask 'bitwarden'
cask 'google-drive'
cask 'notion-calendar'
cask 'obsidian'
cask 'plex'
cask 'private-internet-access'
cask 'spectacle'
cask 'spotify'
cask 'syncthing'
cask 'tailscale'
cask 'visual-studio-code'
cask 'vlc'
cask 'warp'
